
export class ODFModel {
  public booking_ID: any;
  public order_ID: any;
  public shipper_Name: any;
  public shipper_Address1: any;
  public shipper_Address2: any;
  public shipper_City: any;
  public shipper_State: any;
  public shipper_Zip: any;
  public load_Date: any;
  public load_Time_From: any;
  public load_Time_To: any;
  public load_Time_Code: any;
  public shipper_Attention: any;
  public shipper_Email: any;
  public shipper_Phone: any;
  public shipper_Cell: any;
  public origin_Booth: any;
  public origin_FK_Show_ID: any;
  public origin_Air_Code: any;
  public origin_Zone: any;
  public origin_KSMS_Number: any;
  public consignee_Name: any;
  public consignee_Address1: any;
  public consignee_Address2: any;
  public consignee_City: any;
  public consignee_State: any;
  public consignee_Zip: any;
  public delivery_Date: any;
  public delivery_Time_From: any;
  public delivery_Time_To: any;
  public delivery_Time_Code: any;
  public consignee_Attention: any;
  public consignee_Email: any;
  public consignee_Phone: any;
  public consignee_Cell: any;
  public dest_Booth: any;
  public dest_FK_Show_ID: any;
  public dest_Air_Code: any;
  public dest_Zone: any;
  public dest_KSMS_Number: any;
  public pieces: any;
  public weight_Actual_LB: any;
  public weight_Actual_KG: any;
  public weight_Dimensional_LB: any;
  public weight_Dimensional_KG: any;
  public service_Level_Code: any;
  public declared_Value: any;
  public pieces_Description: any;
  public customer_Code: any;
  public tariff_ID: any;
  public current_Editing_By: any;
  public current_Editing_Date: any

}
